---
abstract: 'TF*WebIDF calculator'
author:
  - 'pawa <pawapawa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0
  Test::More: 0.98
  Test::Warn: 0.2
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-JA-TFWebIDF
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Lingua::JA::Halfwidth::Katakana: 0
  Lingua::JA::WebIDF: 0.21
  Text::MeCab: 0.20013
  parent: 0
  perl: 5.8.1
resources:
  bugtracker: https://github.com/pawa-/Lingua-JA-TFWebIDF/issues
  license: http://dev.perl.org/licenses
  repository: https://github.com/pawa-/Lingua-JA-TFWebIDF
version: 0.30
